# Generated by Django 4.1.7 on 2023-03-28 08:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name_ru', models.CharField(max_length=255, verbose_name='Название раздела на русском')),
                ('component_name_en', models.CharField(max_length=255, verbose_name='Название раздела на английском')),
            ],
            options={
                'verbose_name_plural': 'Основные разделы',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name_ru', models.CharField(max_length=255, verbose_name='Название страны на русском')),
                ('country_name_en', models.CharField(max_length=255, verbose_name='Название страны на английском')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name_ru', models.CharField(max_length=255, verbose_name='Название темы на русском')),
                ('topic_name_en', models.CharField(max_length=255, verbose_name='Название темы на английском')),
            ],
            options={
                'verbose_name_plural': 'Темы публикаций',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('authors_full_name', models.CharField(max_length=250, verbose_name='Имя автора')),
                ('authors_discription', wagtail.fields.RichTextField(blank=True, verbose_name='Об авторе')),
                ('authors_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
