# Generated by Django 4.1.7 on 2023-03-28 09:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_components_countries_topics_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('authors_list_discription', wagtail.fields.RichTextField(blank=True, verbose_name='Описание списка автров')),
            ],
            options={
                'verbose_name': 'Список Авторов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Об авторе'},
        ),
    ]
