# Generated by Django 4.1.7 on 2023-04-10 05:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
        ('home', '0004_authorslist_alter_authors_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_author',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.authors'),
        ),
        migrations.CreateModel(
            name='BestPubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('bestpub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.pubs')),
                ('bestpub_parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestpub_list', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Список популярных публикаций',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
