# Generated by Django 4.1.7 on 2023-04-10 07:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
        ('home', '0005_homepage_main_author_bestpublist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('newpub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.pubs')),
                ('newpub_parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='newpub_list', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Список новых публикаций',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
