# Generated by Django 4.1.7 on 2023-06-07 06:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0006_newpublist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avtors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avtor_full_name",
                    models.CharField(max_length=250, verbose_name="Имя автора"),
                ),
                (
                    "avtor_discription",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Об авторе"),
                ),
                (
                    "avtor_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Об авторе",
            },
        ),
    ]
