# Generated by Django 4.1.7 on 2023-06-07 12:19

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_avtors"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="main_avtor",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="home.avtors"
            ),
        ),
    ]
