# Generated by Django 4.1.7 on 2023-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_homepage_main_avtor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Главная страница"},
        ),
        migrations.AddField(
            model_name="components",
            name="component_icon",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Название иконки из библиотеки гугл",
            ),
        ),
    ]
