# Generated by Django 4.1.7 on 2024-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_options_components_component_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_ru', models.CharField(max_length=255, verbose_name='Название тега на русском')),
                ('tag_name_en', models.CharField(max_length=255, verbose_name='Название тега на английском')),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
