# Generated by Django 4.1.7 on 2023-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0006_pubsdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubs",
            name="pubs_count",
            field=models.IntegerField(
                default=0, verbose_name="Всего просмотров публикации"
            ),
        ),
    ]
