# Generated by Django 4.1.7 on 2023-06-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0009_pubs_pubs_avtor"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubs",
            name="pubs_ist",
            field=models.CharField(blank=True, max_length=250, verbose_name="Источник"),
        ),
        migrations.AddField(
            model_name="pubs",
            name="pubs_ist_url",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Ссылка на источник"
            ),
        ),
    ]
