# Generated by Django 4.1.7 on 2024-06-24 11:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tags'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('pubs', '0010_pubs_pubs_ist_pubs_pubs_ist_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubsTags',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='pubs',
            name='pubs_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.tags'),
        ),
    ]
